#easy_admin:
#  site_name: 'DevCollab Admin'
#  entities:
#    User:
#      class: App\Entity\User
#      name_property_path: "email"
#      label: 'Users'
#      list:
#        filters: ['name','lastname','username','location']
#        title: "%%entity_label%% List"
#        actions:
#          - { name: edit, icon: pencil, label: ''}
#          - { name: show, icon: eye, label: '' }
#          - { name: delete, icon: eraser, label: '' }
#        max_results: 15
#        fields:
#          - id
#          - { property: 'name', label: 'First Name'}
#          - { property: 'lastname', label: 'Last Name'}
#          - { property: 'email', type: 'email'}
#          - { property: 'username', label: 'Username'}
#          - location
#          - { property: 'github_username',label: "GitHub" }
#      form:
#        title: "Create User"
#        fields:
#          - { property: 'name', type: 'text', label: 'First Name', type_options: { required: true } }
#          - { property: 'lastname', type: 'text', label: 'Last Name' }
#          - { property: 'email', type: 'email', label: 'Email', type_options: { required: true } }
#          - location
#          - password
#          - { property: 'github_username', type: 'text', label: 'GitHub Username' }
#          - short_description
#    Projects:
#      class: App\Entity\Projects
#      label: 'Projects'
#      list:
#        filters: ['repository','created','deadline']
#        title: "%%entity_label%% List"
#        actions:
#          - { name: edit, icon: pencil, label: ''}
#          - { name: show, icon: eye, label: '' }
#          - { name: delete, icon: eraser, label: '' }
#        fields:
#          - id
#          - { property: 'title', label: 'Title' }
#          - { property: 'repository', label: 'Repository' }
#          - { property: 'created', label: 'Create' }
#          - { property: 'deadline', label: 'Deadline' }
#      form:
#        title: "Create Project"
#        fields:
#          - { property: 'title', label: 'Title' }
#          - { property: 'repository', label: 'Repository' }
#          - { property: 'created', label: 'Create' }
#          - { property: 'deadline', label: 'Deadline' }
#    Teams:
#      class: App\Entity\Teams
#      label: 'Teams'
#      list:
#        title: "%%entity_label%% List"
#        actions:
#          - { name: edit, icon: pencil, label: ''}
#          - { name: show, icon: eye, label: '' }
#          - { name: delete, icon: eraser, label: '' }
#        fields:
#          - id
#          - { property: 'id', label: 'ID' }
#          - { property: 'name', label: 'Team Name' }
#          - { property: 'github_repo', label: 'Github Repository' }
#      form:
#        title: "Create Project"
#        fields:
#          - { property: 'name', label: 'Team Name' }
#          - { property: 'github_repo', label: 'Github Repository' }
#    TeamsPoints:
#      class: App\Entity\teamPoints
#      label: 'Teams Points'
#      list:
#        title: "%%entity_label%%"
#        actions:
#          - { name: edit, icon: pencil, label: ''}
#          - { name: show, icon: eye, label: '' }
#          - { name: delete, icon: eraser, label: '' }
#        fields:
#          - id
#          - { property: 'team_id', label: 'Team ID' }
#          - { property: 'points', label: 'Points' }
#      form:
#        title: "Add Teams"
#        fields:
#          - { property: 'points', label: 'Points' }
#    TeamsTasks:
#      class: App\Entity\teamTasks
#      new:
#        fields: ['name','team_id']
#      Documents:
#        class: App\Entity\Teams
#      label: 'Teams Tasks'
#      list:
#        title: "%%entity_label%%"
#        actions:
#          - { name: edit, icon: pencil, label: ''}
#          - { name: show, icon: eye, label: '' }
#          - { name: delete, icon: eraser, label: '' }
#        fields:
#          - id
#          - { property: 'team_id', label: 'Team ID' }
#          - { property: 'task', label: 'Task Name' }
#          - { property: 'status', label: 'Status' }
#          - { property: 'deadline', label: 'Deadline' }
#      form:
#        title: "Add Teams"
#        fields:
#          - { property: 'team_id', label: 'Team ID' }
#          - { property: 'task', label: 'Task Name' }
#          - { property: 'deadline', label: 'Deadline' }
#
#
#
#    #easy_admin:
##    user:
##        name_property_path: "email"
##    entities:
##        #        # List the entity class name you want to manage
##        #        - App\Entity\Product
##        #        - App\Entity\Category
##        - App\Entity\User
#
##easy_admin:
##site_name: 'DevCollab Admin'
##user:
##display_name: true
##display_avatar: true
##entities:
##Users:
##class: App\Entity\Users
##label: 'Users'
##list:
##filters: ['name','lastname','location']
##title: "%%entity_label%% List"
##actions:
##    - { name: edit, icon: pencil, label: ''}
##    - { name: show, icon: eye, label: '' }
##    - { name: delete, icon: eraser, label: '' }
##max_results: 20
##fields:
##    - id
##    - name
##    - lastname
##    - { property: 'email', type: 'email'}
##    - location
##    - { property: 'github_username',label: "GitHub" }
##form:
##fields:
##    - { property: 'name', type: 'text', label: 'First Name', type_options: { required: true } }
##    - { property: 'lastname', type: 'text', label: 'Last Name' }
##    - { property: 'email', type: 'email', label: 'Email', type_options: { required: true } }
##    - location
##    - password
##    - { property: 'github_username', type: 'text', label: 'GitHub Username' }
##    - short_description
##Skills:
##class: App\Entity\Skills
##list:
##actions:
##    - { name: edit, icon: pencil, label: ''}
##    - { name: show, icon: eye, label: '' }
##    - { name: delete, icon: eraser, label: '' }
##title: "User %%entity_label%% List"
##filters:
##    - { property: 'userfk', label: 'User'}
##    - { property: 'skillfk',label: "Skill" }
##fields:
##    - { property: 'userfk', label: 'User'}
##    - { property: 'skillfk',label: "Skill" }
##Skill:
##class: App\Entity\Skill
##title: "%%entity_label%% List"
##list:
##actions:
##    - { name: edit, icon: pencil, label: ''}
##    - { name: show, icon: eye, label: '' }
##    - { name: delete, icon: eraser, label: '' }
##Teams:
##class: App\Entity\Teams
##actions: ['show']
##list:
##actions:
##    - { name: edit, icon: pencil, label: ''}
##    - { name: show, icon: eye, label: '' }
##    - { name: delete, icon: eraser, label: '' }
##fields:
##    - { property: 'ID', label: 'ID'}
##    - { property: 'Name', label: 'Team Name'}
##    - { property: 'GitHub', label: 'GitHub Repoeixr'}
##    - { property: 'Teampoints', label: 'Team Points'}
##Teampoints:
##class: App\Entity\Teampoints
##Teamtasks:
##class: App\Entity\Teamtasks
##Projects:
##class: App\Entity\Projects
##label: Project Listings
##list:
##actions:
##    - { name: edit, icon: pencil, label: ''}
##    - { name: show, icon: eye, label: '' }
##    - { name: delete, icon: eraser, label: '' }
##fields:
##    - { property: 'ID', label: 'ID'}
##    - { property: 'Title', label: 'Project Title'}
##    - { property: 'teamfk', label: 'Team Name'}
##Projectdetails:
##class: App\Entity\Projectdetails
##label: Project Details
##list:
##actions:
##    - { name: edit, icon: pencil, label: ''}
##    - { name: show, icon: eye, label: '' }
##    - { name: delete, icon: eraser, label: '' }
##fields:
##    - { property: 'projectfk', label: 'Project Name' }
##    - { property: 'repository', label: 'Repository' }
##    - { property: 'Created', label: 'Started at' }
##    - { property: 'Deadline', label: 'Finishes at' }
##    - { property: 'Sprint1', label: 'Sprint Name'}
##    - { property: 'Sprint1Points', label: 'Reward'}
##design:
##brand_color: '#1ABC9C'
##
##menu:
##    - { label: 'Users' }
##    - { entity: 'Users', css_class: 'default', icon: 'user' }
##    - { entity: 'Skills', css_class: 'default', icon: 'book' }
##    - { label: 'Teams' }
##    - { entity: 'Teams', css_class: 'default', icon: 'group' }
##    - { label: 'Admin' }
##    - { entity: 'Skill', css_class: 'default', icon: 'cogs' }
##    - { label: 'Project' }
##    - { entity: 'Projects', css_class: 'default', icon: 'code-branch' }
##    - { entity: 'Projectdetails', css_class: 'default', icon: 'code-branch' }
