easy_admin:
  entities:
    TeamsTasks:
      class: App\Entity\teamTasks
      new:
        fields: ['name','team_id']
      Documents:
        class: App\Entity\Teams
      label: 'Teams Tasks'
      list:
        title: "%%entity_label%%"
        actions:
          - { name: edit, icon: pencil, label: ''}
          - { name: show, icon: eye, label: '' }
          - { name: delete, icon: eraser, label: '' }
        fields:
          - id
          - { property: 'team_id', label: 'Team ID' }
          - { property: 'task', label: 'Task Name' }
          - { property: 'status', label: 'Status' }
          - { property: 'deadline', label: 'Deadline' }
      form:
        title: "Add Teams"
        fields:
          - { property: 'team_id', label: 'Team ID' }
          - { property: 'task', label: 'Task Name' }
          - { property: 'deadline', label: 'Deadline' }